### PR TITLE
DM-17020: Improve docsteady test plan and report generation

### PR DESCRIPTION
**Pull request by brianv0**

### CODE REVIEW

**Comment by brianv0** [comment]
@gcomoretto This looks good. I did some code cleanup (see commit 762703a) where I got rid of the `TestIssue` class object (it's unused, since the `Issue` object is better) and I just changed the names a bit in the template and some local variable names so it's a bit more clear what's going on (`issue` vs `issue_key`, where `issue` should refer to the object and not just the key).

It seems like `citeds` is working fine? Were you having issues with it?

**Comment by gcomoretto** [comment]
Thank you for the changes. 
However citeds is not working as I was expecting. In my original implementation, each multiline field is parsed in order to identify citations, and add the corresponding \citeds{}. You can see that in sectino 1.2 of https://dmtr-102.lsst.io/v/DM-16674/index.html LDM-503 is is not rendered. Also, you have to note that LDM-503-8b shall not be remndered.

**Comment by timj** [comment]
I see that there are some sections of the document that have LDM-503 mentioned without citeds. Are the "applicable documents" handled differently? Maybe there is a problem with your {{re.sub}} command?

**Comment by brianv0** [comment]
It couldn't find the `LDM-503\\`, and I had code to not use the word boundary because it was matching (LDM-503)-8b, but a negative lookahead fixed that.

**Pull request merged**
